#!/usr/bin/env python3

import argparse
import csv
import json
from collections import defaultdict
from pathlib import Path

import numpy as np


def parse_arguments():
    parser = argparse.ArgumentParser(
        description='Build LSTM windows from cleaned trajectory CSV.'
    )

    parser.add_argument(
        'input_csv',
        help='Cleaned CSV generated by build_dataset.py',
    )

    parser.add_argument(
        'output_directory',
        help='Directory used to store NPZ datasets and metadata',
    )

    parser.add_argument(
        '--history-steps',
        type=int,
        default=20,
        help='Number of past frames, default: 20',
    )

    parser.add_argument(
        '--prediction-steps',
        type=int,
        default=30,
        help='Number of future frames, default: 30',
    )

    parser.add_argument(
        '--stride',
        type=int,
        default=1,
        help='Sliding-window stride, default: 1',
    )

    parser.add_argument(
        '--train-ratio',
        type=float,
        default=0.70,
        help='Training ratio, default: 0.70',
    )

    parser.add_argument(
        '--validation-ratio',
        type=float,
        default=0.15,
        help='Validation ratio, default: 0.15',
    )

    parser.add_argument(
        '--sample-dt',
        type=float,
        default=0.1,
        help='Sampling interval in seconds, default: 0.1',
    )

    return parser.parse_args()


def load_segments(csv_path):
    segments = defaultdict(list)

    with csv_path.open(encoding='utf-8') as csv_file:
        reader = csv.DictReader(csv_file)

        required_fields = {
            'obstacle_id',
            'segment_id',
            'sample_index',
            'timestamp',
            'x',
            'y',
            'vx',
            'vy',
        }

        if reader.fieldnames is None:
            raise RuntimeError('CSV header was not found.')

        missing_fields = required_fields - set(reader.fieldnames)

        if missing_fields:
            raise RuntimeError(
                f'Input CSV is missing fields: {sorted(missing_fields)}'
            )

        for row in reader:
            segment_id = row['segment_id']

            segments[segment_id].append({
                'obstacle_id': row['obstacle_id'],
                'sample_index': int(row['sample_index']),
                'timestamp': float(row['timestamp']),
                'x': float(row['x']),
                'y': float(row['y']),
                'vx': float(row['vx']),
                'vy': float(row['vy']),
            })

    for segment_id in segments:
        segments[segment_id].sort(
            key=lambda sample: sample['sample_index']
        )

    return segments


def split_segment(
    samples,
    train_ratio,
    validation_ratio,
):
    sample_count = len(samples)

    train_end = int(sample_count * train_ratio)

    validation_end = int(
        sample_count * (
            train_ratio + validation_ratio
        )
    )

    return {
        'train': samples[:train_end],
        'validation': samples[
            train_end:validation_end
        ],
        'test': samples[validation_end:],
    }


def build_windows(
    samples,
    history_steps,
    prediction_steps,
    stride,
):
    input_windows = []
    target_windows = []
    metadata = []

    total_steps = history_steps + prediction_steps

    if len(samples) < total_steps:
        return input_windows, target_windows, metadata

    last_start = len(samples) - total_steps

    for start_index in range(
        0,
        last_start + 1,
        stride,
    ):
        history = samples[
            start_index:
            start_index + history_steps
        ]

        future = samples[
            start_index + history_steps:
            start_index + total_steps
        ]

        current_x = history[-1]['x']
        current_y = history[-1]['y']

        input_window = []

        for sample in history:
            input_window.append([
                sample['x'] - current_x,
                sample['y'] - current_y,
                sample['vx'],
                sample['vy'],
            ])

        target_window = []

        for sample in future:
            target_window.append([
                sample['x'] - current_x,
                sample['y'] - current_y,
            ])

        input_windows.append(input_window)
        target_windows.append(target_window)

        metadata.append({
            'obstacle_id': history[-1]['obstacle_id'],
            'segment_id': (
                history[-1].get(
                    'segment_id',
                    ''
                )
            ),
            'start_timestamp': history[0]['timestamp'],
            'current_timestamp': history[-1]['timestamp'],
            'future_end_timestamp': future[-1]['timestamp'],
            'current_x': current_x,
            'current_y': current_y,
        })

    return input_windows, target_windows, metadata


def calculate_statistics(array):
    axes = tuple(range(array.ndim - 1))

    mean = array.mean(
        axis=axes,
        dtype=np.float64,
    )

    std = array.std(
        axis=axes,
        dtype=np.float64,
    )

    std = np.where(
        std < 1e-8,
        1.0,
        std,
    )

    return mean, std


def normalize(array, mean, std):
    return (
        (array - mean) / std
    ).astype(np.float32)


def save_metadata_csv(path, metadata_rows):
    fieldnames = [
        'obstacle_id',
        'segment_id',
        'start_timestamp',
        'current_timestamp',
        'future_end_timestamp',
        'current_x',
        'current_y',
    ]

    with path.open(
        'w',
        newline='',
        encoding='utf-8',
    ) as csv_file:
        writer = csv.DictWriter(
            csv_file,
            fieldnames=fieldnames,
        )

        writer.writeheader()
        writer.writerows(metadata_rows)


def main():
    args = parse_arguments()

    if args.history_steps <= 0:
        raise ValueError('history-steps must be positive.')

    if args.prediction_steps <= 0:
        raise ValueError('prediction-steps must be positive.')

    if args.stride <= 0:
        raise ValueError('stride must be positive.')

    if not 0.0 < args.train_ratio < 1.0:
        raise ValueError('train-ratio must be between 0 and 1.')

    if not 0.0 < args.validation_ratio < 1.0:
        raise ValueError(
            'validation-ratio must be between 0 and 1.'
        )

    if (
        args.train_ratio
        + args.validation_ratio
        >= 1.0
    ):
        raise ValueError(
            'train-ratio + validation-ratio must be less than 1.'
        )

    input_csv = Path(
        args.input_csv
    ).expanduser().resolve()

    output_directory = Path(
        args.output_directory
    ).expanduser().resolve()

    if not input_csv.is_file():
        raise FileNotFoundError(
            f'Input CSV does not exist: {input_csv}'
        )

    output_directory.mkdir(
        parents=True,
        exist_ok=True,
    )

    segments = load_segments(input_csv)

    if not segments:
        raise RuntimeError('No trajectory segments were loaded.')

    split_inputs = {
        'train': [],
        'validation': [],
        'test': [],
    }

    split_targets = {
        'train': [],
        'validation': [],
        'test': [],
    }

    split_metadata = {
        'train': [],
        'validation': [],
        'test': [],
    }

    for segment_id, samples in segments.items():
        for sample in samples:
            sample['segment_id'] = segment_id

        partitions = split_segment(
            samples,
            args.train_ratio,
            args.validation_ratio,
        )

        print()
        print(f'Processing {segment_id}')
        print(f'  total frames: {len(samples)}')

        for split_name, split_samples in partitions.items():
            inputs, targets, metadata = build_windows(
                split_samples,
                args.history_steps,
                args.prediction_steps,
                args.stride,
            )

            split_inputs[split_name].extend(inputs)
            split_targets[split_name].extend(targets)
            split_metadata[split_name].extend(metadata)

            print(
                f'  {split_name}: '
                f'{len(split_samples)} frames, '
                f'{len(inputs)} windows'
            )

    arrays = {}

    for split_name in [
        'train',
        'validation',
        'test',
    ]:
        if not split_inputs[split_name]:
            raise RuntimeError(
                f'No windows were created for {split_name}.'
            )

        arrays[split_name] = {
            'inputs': np.asarray(
                split_inputs[split_name],
                dtype=np.float32,
            ),
            'targets': np.asarray(
                split_targets[split_name],
                dtype=np.float32,
            ),
        }

    input_mean, input_std = calculate_statistics(
        arrays['train']['inputs']
    )

    target_mean, target_std = calculate_statistics(
        arrays['train']['targets']
    )

    for split_name in [
        'train',
        'validation',
        'test',
    ]:
        raw_inputs = arrays[split_name]['inputs']
        raw_targets = arrays[split_name]['targets']

        normalized_inputs = normalize(
            raw_inputs,
            input_mean,
            input_std,
        )

        normalized_targets = normalize(
            raw_targets,
            target_mean,
            target_std,
        )

        output_path = (
            output_directory
            / f'smoke_002_{split_name}.npz'
        )

        np.savez_compressed(
            output_path,
            inputs=normalized_inputs,
            targets=normalized_targets,
            raw_inputs=raw_inputs,
            raw_targets=raw_targets,
        )

        metadata_path = (
            output_directory
            / f'smoke_002_{split_name}_metadata.csv'
        )

        save_metadata_csv(
            metadata_path,
            split_metadata[split_name],
        )

        print()
        print(f'Saved {split_name}: {output_path}')
        print(f'  inputs: {normalized_inputs.shape}')
        print(f'  targets: {normalized_targets.shape}')

    normalization = {
        'input_features': [
            'relative_x',
            'relative_y',
            'vx',
            'vy',
        ],
        'target_features': [
            'future_relative_x',
            'future_relative_y',
        ],
        'input_mean': input_mean.tolist(),
        'input_std': input_std.tolist(),
        'target_mean': target_mean.tolist(),
        'target_std': target_std.tolist(),
    }

    normalization_path = (
        output_directory
        / 'normalization.json'
    )

    with normalization_path.open(
        'w',
        encoding='utf-8',
    ) as json_file:
        json.dump(
            normalization,
            json_file,
            indent=2,
        )

    dataset_metadata = {
        'source_csv': str(input_csv),
        'sampling_frequency_hz': (
            1.0 / args.sample_dt
        ),
        'sample_dt': args.sample_dt,
        'history_steps': args.history_steps,
        'history_duration_seconds': (
            args.history_steps
            * args.sample_dt
        ),
        'prediction_steps': args.prediction_steps,
        'prediction_duration_seconds': (
            args.prediction_steps
            * args.sample_dt
        ),
        'stride': args.stride,
        'train_ratio': args.train_ratio,
        'validation_ratio': args.validation_ratio,
        'test_ratio': (
            1.0
            - args.train_ratio
            - args.validation_ratio
        ),
        'split_strategy': (
            'chronological split within each trajectory segment'
        ),
        'warning': (
            'This smoke dataset uses fixed routes and speed. '
            'It validates the pipeline but is not the final '
            'competition training dataset.'
        ),
    }

    metadata_path = (
        output_directory
        / 'dataset_metadata.json'
    )

    with metadata_path.open(
        'w',
        encoding='utf-8',
    ) as json_file:
        json.dump(
            dataset_metadata,
            json_file,
            indent=2,
        )

    print()
    print('Dataset construction completed.')
    print(f'Output directory: {output_directory}')
    print(f'Input mean: {input_mean}')
    print(f'Input std: {input_std}')
    print(f'Target mean: {target_mean}')
    print(f'Target std: {target_std}')


if __name__ == '__main__':
    main()
