# The YAML order defines task execution order.
mission_mapping:
  x:
    color: red
    destination: A
    objects:
      - red_cube_1
      - red_cube_2
      - red_cube_3
      - red_cube_4
      - red_cube_5

  y:
    color: blue
    destination: B
    objects:
      - blue_cube_1
      - blue_cube_2
      - blue_cube_3
      - blue_cube_4
      - blue_cube_5
