<?xml version="1.0"?>
<package format="3">
  <name>moon_warehouse_moveit</name>
  <version>0.1.0</version>
  <description>Configuration-driven fixed pick/place execution.</description>
  <maintainer email="team@example.com">moon warehouse team</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>control_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend>
  <exec_depend>builtin_interfaces</exec_depend>
  <exec_depend>linkattacher_msgs</exec_depend>
  <exec_depend>moon_warehouse_interfaces</exec_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
