cmake_minimum_required(VERSION 3.8)
project(gazebo_obstacle_plugin)
find_package(ament_cmake REQUIRED)
find_package(gazebo_dev REQUIRED)
find_package(gazebo_msgs REQUIRED)
find_package(rclcpp REQUIRED)
find_package(geometry_msgs REQUIRED)
add_library(auto_move_obstacle SHARED src/AutoMoveObstaclePlugin.cc)
target_include_directories(auto_move_obstacle PUBLIC include)
ament_target_dependencies(auto_move_obstacle gazebo_dev gazebo_msgs rclcpp geometry_msgs)
target_link_libraries(auto_move_obstacle ${GAZEBO_LIBRARIES})
install(TARGETS auto_move_obstacle LIBRARY DESTINATION lib)
ament_package()